version: '3'
services:
  postgres:
    image: 'postgres:12'
    restart: 'always'
    volumes:
      - '../../data/postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    networks:
      - vm-default
networks:
  vm-default:
    external: true
    driver: bridge
