version: '3'
services:
  keycloack:
    image: 'quay.io/keycloak/keycloak:15.0.2'
    restart: 'always'
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
    ports:
      - '5090:8080'
    networks:
      - vm-default
networks:
  vm-default:
    external: true
    driver: bridge
